{% set name = "pydumpling" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydumpling-{{ version }}.tar.gz
  sha256: 9ec944a9b8b9ddf367e008f4e819ff535d6a8f393aebb62be9a6a7e6eaaf532f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pdm-backend
    - pip
  run:
    - python >=3.7
    - dill <1.0.0,>=0.3.2
    - packaging >=24.0

test:
  imports:
    - pydumpling
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cocolato/pydumpling
  doc_url: https://pydumpling.readthedocs.io/
  summary: Python post-mortem debugger
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
